//{{NO_DEPENDENCIES}}
// Archivo de inclusión generado de Microsoft Visual C++.
// Usado por PIAESTDAT.rc
//
#define BV_Buscar                       2
#define CP_Examinar                     2
#define BV_Cancelar                     3
#define CP_Buscar                       3
#define BV_BuscarMarca                  4
#define CV_Buscar                       5
#define CP_Examina                      6
#define V_Bienvenida                    9
#define V_Login                         103
#define V_MenuPrincipal                 106
#define V_Registro                      107
#define V_RegistrarPersona              111
#define V_RegistrarVacuna               113
#define V_RegistrarCarnet               115
#define V_EliminarVacuna                117
#define V_EliminarCarnet                118
#define V_EditarPersona                 119
#define V_EditarCarnet                  121
#define V_EditarVacuna                  123
#define V_EditPersona                   125
#define V_BusCarnet                     126
#define V_BusquedaCarnet                127
#define V_ReportesPersonas              129
#define V_BusReporte                    130
#define IDC_EDIT1                       1002
#define AU_Nombre                       1002
#define AC_CURP                         1002
#define BV_Marca                        1002
#define CP_Dato                         1002
#define CV_Marca                        1002
#define CC_Carnet                       1002
#define BBCC_Dato                       1002
#define RP_Nombre                       1002
#define IDC_EDIT2                       1003
#define AU_ApellidoP                    1003
#define AC_Nombre                       1003
#define BV_Tipo                         1003
#define CP_Nombre                       1003
#define CV_Clave                        1003
#define CC_Nombre                       1003
#define BBCC_Nombre                     1003
#define RP_ApellidoP                    1003
#define IDC_BUTTON1                     1004
#define AV_Guardar                      1004
#define AC_BuscaCURP                    1004
#define BV_Clave                        1004
#define CP_ApellidoM                    1004
#define CV_Descripcion                  1004
#define CC_ApellidoM                    1004
#define BBCC_ApellidoP                  1004
#define RP_Reportes                     1004
#define IDC_BUTTON3                     1005
#define AP_Guardar                      1005
#define BV_Dosis                        1005
#define CP_ApellidoP                    1005
#define CV_TipoAnterior                 1005
#define CC_ApellidoP                    1005
#define BBCC_FechaNacimiento            1005
#define RP_ApellidoM                    1005
#define IDC_BUTTON2                     1006
#define IDC_EDIT6                       1006
#define AV_Dosis                        1006
#define AC_ApellidoM                    1006
#define BV_Descripcion                  1006
#define CP_Edad                         1006
#define CV_DosisReq                     1006
#define CC_FechaNacimiento              1006
#define BBCC_ApellidoM                  1006
#define RP_Sexo                         1006
#define IDC_EDIT7                       1007
#define AV_VacunasRecibidas             1007
#define AC_ApellidoP                    1007
#define BV_Vacunas                      1007
#define CP_SexoAnterior                 1007
#define CV_VacunasImp                   1007
#define CC_Sexo                         1007
#define BBCC_Edad                       1007
#define RP_Edad                         1007
#define IDC_EDIT3                       1008
#define IDC_EDIT14                      1008
#define AV_Clave                        1008
#define AU_ApellidoM                    1008
#define AC_FechaNacimiento              1008
#define BV_Precio                       1008
#define CP_FechaNacimientoAnterior      1008
#define CV_Precio                       1008
#define CC_Edad                         1008
#define BBCC_Sexo                       1008
#define RP_Nacimiento                   1008
#define IDC_EDIT4                       1009
#define IDC_EDIT15                      1009
#define AV_Descripcion                  1009
#define AU_Usuario                      1009
#define AC_Edad                         1009
#define BC_Dosis                        1009
#define CP_EstadoCivilAnterior          1009
#define CC_VacunaAAplicarAnterior       1009
#define BBCC_VacunaAplicar              1009
#define RP_EstadoCivil                  1009
#define IDC_EDIT5                       1010
#define IDC_EDIT8                       1010
#define IDC_EDIT16                      1010
#define AP_Colonia                      1010
#define AV_Precio                       1010
#define AU_Contrasena                   1010
#define AC_Sexo                         1010
#define BC_Sexo                         1010
#define CP_GrupoOc                      1010
#define CC_Dosis                        1010
#define BBCC_TipoVacuna                 1010
#define RP_GrupoOcupacional             1010
#define IDC_EDIT9                       1011
#define AP_Ciudad                       1011
#define AC_BuscaVacuna                  1011
#define BC_Vacuna                       1011
#define CP_PerfilRiesgo                 1011
#define CC_FechaAplicacionAnterior      1011
#define BBCC_LugarAplicacion            1011
#define RP_Telefono                     1011
#define IDC_EDIT10                      1012
#define AP_Estado                       1012
#define BC_Lugar                        1012
#define CP_Telefono                     1012
#define CC_ProximaDosisAnterior         1012
#define BBCC_FechaAplicacion            1012
#define RP_PerfilRiesgo                 1012
#define IDC_EDIT11                      1013
#define AP_Telefono                     1013
#define BC_ProxDosis                    1013
#define CP_Numero                       1013
#define CC_Lugar                        1013
#define BBCC_ProximaDosis               1013
#define IDC_EDIT12                      1014
#define AP_GpoOcupacional               1014
#define CP_Calle                        1014
#define RP_RFC                          1014
#define IDC_EDIT13                      1015
#define AP_PerfilRiesgo                 1015
#define AC_Precio                       1015
#define CP_Colonia                      1015
#define BBCC_DosisAplicar               1015
#define RP_CURP                         1015
#define IDC_DATETIMEPICKER1             1016
#define AP_FechaNacimiento              1016
#define AC_FechaDosisActual             1016
#define CP_FechaNacimiento              1016
#define CC_FechaAplicacion              1016
#define RP_Calle                        1016
#define AC_TipoVacuna                   1017
#define CP_Ciudad                       1017
#define CC_ProximaDosis                 1017
#define RP_Colonia                      1017
#define IDC_COMBO2                      1018
#define AP_EstadoCivil                  1018
#define CP_Estado                       1018
#define RP_Numero                       1018
#define IDC_COMBO3                      1019
#define IDC_COMBO1                      1019
#define AP_Sexo                         1019
#define AV_Tipo                         1019
#define AC_Vacuna                       1019
#define CP_Sexo                         1019
#define CV_Tipo                         1019
#define CC_VacunaAAplicar               1019
#define RP_Ciudad                       1019
#define B_RegistroUsuario               1020
#define AC_Lote                         1020
#define CP_EstadoCivil                  1020
#define B_Login                         1021
#define CP_CodigoPostal                 1021
#define RP_Estado                       1021
#define Login_Usuario                   1022
#define AC_Dosis                        1022
#define RP_Marca                        1022
#define Login_Contrasena                1023
#define RP_DosisActual                  1023
#define RegistroU_Guardar               1024
#define AU_Guardar                      1024
#define RP_UltimaDosis                  1024
#define AP_Examinar                     1025
#define AC_Lugar                        1025
#define RP_ProximaDosis                 1025
#define AP_Foto                         1026
#define AC_FechaDosisSiguiente          1026
#define AP_Edad                         1027
#define AP_ApellidoP                    1028
#define AP_ApellidoM                    1029
#define AP_Curp                         1030
#define AP_Rfc                          1031
#define AP_Calle                        1032
#define AP_Numero                       1033
#define AP_CodigoPostal                 1034
#define AV_Marca                        1034
#define AP_Nombre                       1035
#define AC_Registrar                    1035
#define AC_Foto                         1036
#define BV_Eliminar                     1037
#define BC_Buscar                       1038
#define BC_Carnet                       1039
#define BC_Nombre                       1040
#define BC_ApellidoP                    1041
#define BC_ApellidoM                    1042
#define BC_Edad                         1043
#define BC_FechaNacimiento              1044
#define BC_Eliminar                     1045
#define BC_Cancelar                     1046
#define BC_Foto                         1047
#define CP_Static                       1048
#define CP_Editar                       1049
#define CP_Foto                         1050
#define CV_Editar                       1051
#define CC_Editar                       1052
#define CC_Buscar                       1053
#define CC_Foto                         1054
#define BBCC_ListaBusqueda              1055
#define BBCC_Buscar                     1056
#define BBCC_Foto                       1057
#define BBCC_Cambio                     1058
#define RP_Lista                        1059
#define RP_Foto                         1060
#define ID_REGISTRO_PERSONAS            40001
#define ID_REGISTRO_VACUNAS             40002
#define ID_REGISTRO_CARNET              40003
#define ID_MODIFICAR_PERSONAS           40004
#define ID_MODIFICAR_VACUNAS            40005
#define ID_MODIFICAR_CARNET             40006
#define ID_BAJA_VACUNA                  40007
#define ID_BAJA_CARNET                  40008
#define ID_REPORTE_REPORTE              40009
#define M_Salir                         40010
#define ID_Salir                        40011
#define ID_REGISTRO_PERSONA             40012
#define ID_REGISTRO_VACUNA              40013
#define ID_MODIFICAR_PERSONA            40014
#define ID_MODIFICAR_VACUNA             40015
#define ID_REPORTE                      40016
#define ID_BUSCAR_CARNET                40017
#define E_PorCURP                       40018
#define E_PorRFC                        40019
#define B_NombreSec                     40020
#define B_CarnetSec                     40021
#define B_CarnetBin                     40022
#define ID_PORCARNET                    40023
#define RP_CarnetHeap                   40024
#define RP_NombreQuick                  40025

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        132
#define _APS_NEXT_COMMAND_VALUE         40026
#define _APS_NEXT_CONTROL_VALUE         1061
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
